version: 2
updates:
  - package-ecosystem: composer
    directory: /api
    schedule:
      interval: weekly
    groups:
      php-dependencies:
        patterns: ["*"]
    ignore:
      - dependency-name: phpunit/phpunit
        update-types: ["version-update:semver-major"]
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      web-dependencies:
        patterns: ["*"]
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      - dependency-name: typescript
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
