<?php

return [
    ['name' => 'Nora Benali', 'role' => 'Développeuse backend', 'years' => '2018 2021 2025', 'skills' => 'Laravel PHP PostgreSQL Redis API REST tests automatisés Docker', 'summary' => 'Conception de services SaaS, files asynchrones et revues de code.'],
    ['name' => 'Hugo Lambert', 'role' => 'Développeur full-stack', 'years' => '2019 2022 2026', 'skills' => 'Laravel Vue TypeScript PostgreSQL Redis Vitest PHPUnit', 'summary' => 'Développement de produits B2B et accompagnement des mises en production.'],
    ['name' => 'Sarah Diallo', 'role' => 'Ingénieure logiciel', 'years' => '2017 2020 2025', 'skills' => 'PHP Laravel Vue TypeScript Docker PostgreSQL tests automatisés', 'summary' => 'Architecture applicative, qualité logicielle et mentorat technique.'],
    ['name' => 'Louis Garnier', 'role' => 'Développeur frontend', 'years' => '2020 2023 2026', 'skills' => 'Vue TypeScript JavaScript accessibilité tests automatisés API Laravel', 'summary' => 'Interfaces métier simples connectées à des API documentées.'],
    ['name' => 'Inès Robert', 'role' => 'Tech lead PHP', 'years' => '2015 2019 2025', 'skills' => 'Laravel PHP PostgreSQL Redis Docker CI/CD PHPUnit Vue', 'summary' => 'Pilotage technique de plateformes à fort volume et traitements en queue.'],
    ['name' => 'Mehdi Caron', 'role' => 'Développeur web', 'years' => '2021 2024 2026', 'skills' => 'Laravel Vue TypeScript PostgreSQL Tailwind tests automatisés', 'summary' => 'Livraison itérative de fonctionnalités SaaS orientées utilisateurs.'],
    ['name' => 'Chloé Marchand', 'role' => 'Ingénieure backend', 'years' => '2018 2022 2025', 'skills' => 'PHP Laravel Redis PostgreSQL RabbitMQ Docker observabilité', 'summary' => 'Fiabilisation de workers asynchrones et optimisation de bases de données.'],
    ['name' => 'Adam Petit', 'role' => 'Développeur full-stack', 'years' => '2019 2021 2026', 'skills' => 'Vue TypeScript Laravel PHP PostgreSQL Redis Playwright', 'summary' => 'Applications métiers, tests end-to-end et design systems.'],
    ['name' => 'Lina Fontaine', 'role' => 'Développeuse PHP', 'years' => '2016 2020 2025', 'skills' => 'Laravel PHP Symfony PostgreSQL Redis PHPUnit Docker', 'summary' => 'Migration progressive de monolithes et amélioration de la couverture de tests.'],
    ['name' => 'Gabriel Muller', 'role' => 'Software engineer', 'years' => '2018 2023 2026', 'skills' => 'Laravel Vue TypeScript PostgreSQL Redis Kubernetes tests automatisés', 'summary' => 'Conception de produits multi-tenant et automatisation des déploiements.'],
    ['name' => 'Maya Rousseau', 'role' => 'Développeuse junior', 'years' => '2023 2024 2026', 'skills' => 'PHP Laravel Vue TypeScript PostgreSQL Git tests', 'summary' => 'Premières expériences solides sur un SaaS et forte pratique des tests.'],
    ['name' => 'Noé Faure', 'role' => 'Développeur API', 'years' => '2017 2021 2025', 'skills' => 'Laravel PHP API REST PostgreSQL Redis sécurité Docker', 'summary' => 'API partenaires, authentification et suivi de performance.'],
    ['name' => 'Aya Mercier', 'role' => 'Product engineer', 'years' => '2019 2022 2026', 'skills' => 'Vue TypeScript Laravel PostgreSQL UX tests automatisés', 'summary' => 'Collaboration produit et réalisation de parcours métier accessibles.'],
    ['name' => 'Tom Nguyen', 'role' => 'DevOps applicatif', 'years' => '2016 2020 2025', 'skills' => 'Docker Redis PostgreSQL Laravel CI/CD monitoring Linux', 'summary' => 'Industrialisation de plateformes PHP et supervision de files de messages.'],
    ['name' => 'Zoé Lemoine', 'role' => 'Développeuse mobile', 'years' => '2019 2022 2025', 'skills' => 'Swift Kotlin Firebase iOS Android tests mobiles', 'summary' => 'Applications mobiles grand public et publication sur les stores.'],
    ['name' => 'Yanis Lopez', 'role' => 'Data analyst', 'years' => '2018 2021 2025', 'skills' => 'Python SQL Tableau Power BI statistiques entrepôt de données', 'summary' => 'Tableaux de bord financiers et analyses prédictives.'],
    ['name' => 'Emma Chevalier', 'role' => 'Designer produit', 'years' => '2017 2020 2026', 'skills' => 'Figma recherche utilisateur prototypage design system accessibilité', 'summary' => 'Conception de parcours numériques et ateliers utilisateurs.'],
    ['name' => 'Rayan Picard', 'role' => 'Commercial B2B', 'years' => '2016 2022 2025', 'skills' => 'prospection négociation CRM grands comptes anglais', 'summary' => 'Développement de portefeuilles clients dans les services numériques.'],
    ['name' => 'Louise Henry', 'role' => 'Responsable RH', 'years' => '2015 2020 2025', 'skills' => 'recrutement formation droit social SIRH management', 'summary' => 'Structuration de processus RH dans des entreprises en croissance.'],
    ['name' => 'Ilyes Renaud', 'role' => 'Technicien support', 'years' => '2020 2023 2026', 'skills' => 'support utilisateurs Windows réseau ITIL ticketing', 'summary' => 'Assistance de proximité et administration de postes de travail.'],
];
