import { createI18n } from 'vue-i18n'

export const messages = {
  fr: {
    nav: { main: 'Navigation principale', dashboard: 'Suivi', settings: 'Configuration', recruiter: 'Espace RH', logout: 'Se déconnecter' },
    footer: { promise: 'Chaque candidature mérite une réponse.', support: 'Soutenir le développement' },
    home: {
      eyebrow: 'Recrutement responsable, assisté par IA',
      title: "Plus d'excuses : chaque candidature mérite une réponse, même si elle est automatisée.",
      problem: 'Le recrutement est devenu un cercle vicieux : face aux annonces parfois fictives et aux candidatures qui restent sans réponse, les candidats automatisent leurs envois. Les recruteurs reçoivent alors toujours plus de candidatures difficiles à traiter, ce qui produit encore davantage de silence.',
      lead: 'no-excuse brise cette boucle : les recruteurs gagnent du temps grâce au filtrage et à la priorisation des candidatures, tandis que chaque candidat reçoit une réponse claire, qu’il soit retenu ou non. Les profils pertinents sont scorés par critère et présentés dans un top 10 pour une décision qui reste humaine.',
      recruiterCta: 'Connexion RH — instance installée', installCta: 'Installer avec Docker', loginCta: 'Se connecter', demoCta: 'Tester la démo', demoFull: 'Démo complète', demoStarting: 'Préparation des 20 CV…', demoPromise: '{count} CV fictifs, aucune IA payante, espace supprimé après {hours} h.', demoActiveSessions: 'Sandboxes actuellement servies : {count} / {max}.', demoCapacityTransition: 'Capacité désormais limitée à {max} · {count} anciennes sandboxes restent actives jusqu’à leur déconnexion ou expiration.', waitlistLead: 'Démo complète ? Recevez un unique e-mail lorsqu’une place se libère.', waitlistPlaceholder: "vous{'@'}entreprise.fr", waitlistCta: 'Me prévenir', waitlistSuccess: 'Inscription enregistrée. Nous vous préviendrons dès qu’une place se libère.', waitlistQueueTitle: 'File d’attente', waitlistQueueCount: 'Inscriptions en attente : {count}', waitlistQueueEmpty: 'Personne n’attend encore. Vous pouvez être le premier à vous inscrire.', waitlistPrivacy: 'Les adresses sont chiffrées et ne sont jamais publiées.', waitlistYou: 'Vous', waitlistPrivate: 'Inscription privée', accessEyebrow: 'Quel accès choisir ?', accessTitle: 'Trois parcours, sans ambiguïté.', accessPublicTitle: 'Testez la démo ou installez votre propre instance.', accessDemoTitle: 'Je veux tester', accessDemoText: 'Sur no-excuse.pro, lancez une sandbox RH temporaire avec 20 CV fictifs. Aucun compte, mot de passe ou e-mail requis tant qu’une place est disponible.', accessInstallTitle: 'Je veux l’utiliser dans mon entreprise', accessInstallText: 'Un développeur installe no-excuse avec Docker sur l’infrastructure de l’entreprise. Le premier RH crée ensuite le compte responsable.', accessLoginTitle: 'Mon entreprise l’a déjà installé', accessLoginText: 'Connectez-vous sur l’adresse no-excuse fournie par votre entreprise avec le compte créé par le responsable RH.',
      metricOne: '2 files IA', metricOneText: 'Un filtre économique, puis une analyse fine.',
      metricTwo: 'Top 10', metricTwoText: 'Une sélection lisible pour la décision humaine.',
      metricThree: '100 %', metricThreeText: 'Des candidats informés à la fin du processus.',
      privacyEyebrow: 'Confidentialité avant IA',
      privacyTitle: 'Les CV sont anonymisés localement avant tout envoi vers un LLM.',
      privacyText: 'Les noms, coordonnées, adresses et autres identifiants directs sont masqués sur votre instance. Seul le texte pseudonymisé est transmis au fournisseur d’IA ; si cette protection locale échoue, aucun appel distant n’est effectué.',
      workflow: 'Un processus privé et traçable', step1: 'Connecter', step1Text: 'LinkedIn, un ATS ou votre site transmet le CV à l’API sécurisée.',
      step2: 'Qualifier', step2Text: 'Deux modèles configurables filtrent puis scorent.',
      step3: 'Décider', step3Text: 'Le RH annote, réordonne et choisit humainement.', supportEyebrow: 'Open source indépendant', supportTitle: 'Soutenir no-excuse et Sonomundi', supportText: 'Ces outils sont développés ouvertement et demandent du temps, des serveurs et beaucoup de café. Un soutien aide à faire avancer no-excuse et Sonomundi.', supportCta: 'Soutenir sur Ko-fi', sonomundiCta: 'Découvrir la démo Sonomundi',
    },
    offers: { title: 'Offres ouvertes', lead: 'Des campagnes avec une date de clôture et un engagement de réponse.', empty: 'Aucune offre ouverte pour le moment.', apply: 'Voir et candidater', closes: 'Clôture le' },
    apply: { title: 'Candidater', criteria: 'Critères annoncés', name: 'Nom complet', email: 'Adresse e-mail', letter: 'Message de motivation', cv: 'CV au format PDF', submit: 'Envoyer ma candidature', success: 'Candidature enregistrée', tokenWarning: 'Copiez ce jeton maintenant : il ne sera plus affiché.', track: 'Suivre cette candidature' },
    auth: { title: 'Découvrir le backoffice RH', lead: 'Testez le suivi des candidatures et explorez sa configuration.', login: 'Se connecter', name: 'Nom', email: 'E-mail', password: 'Mot de passe', passwordRules: '12 caractères minimum, avec majuscule, minuscule et chiffre.', confirmation: 'Confirmation', mfaCode: 'Code reçu par e-mail', promise: 'Une décision assistée, jamais automatisée.', invitation: 'Invitation sécurisée', activateLead: 'Choisissez votre mot de passe pour rejoindre l’équipe RH.', activate: 'Activer mon accès', forgotPassword: 'Mot de passe oublié ?', reset: 'Réinitialiser le mot de passe', resetLead: 'Recevez un lien sécurisé si ce compte existe.', resetSent: 'Si ce compte existe, le lien vient d’être envoyé.', sendReset: 'Envoyer le lien', choosePassword: 'Choisissez un nouveau mot de passe.', teamOnly: 'Accès à votre installation', publicDemoTitle: 'Démo publique', demoAccessTitle: 'Tester no-excuse maintenant', publicDemoText: 'Une sandbox RH temporaire sera créée automatiquement avec 20 candidatures fictives. Aucun compte, mot de passe ou e-mail n’est demandé.', demoBackofficeHelp: 'La configuration détaillée du backoffice sera visible en lecture seule depuis la sandbox.', installedInstanceHelp: 'Cette connexion fonctionne uniquement avec l’adresse et le compte fournis par votre entreprise. Lors d’une première installation, le compte responsable est créé automatiquement au premier accès.' },
    setup: { eyebrow: 'Première installation', title: 'Prêt en trois étapes.', lead: 'Créez l’entreprise et le premier compte responsable. Aucun réglage technique n’est nécessaire ici.', step1: 'Entreprise et responsable', step2: 'IA, e-mails et équipe', step3: 'Première annonce', companyAndOwner: 'Créer votre espace', company: 'Nom de l’entreprise', ownerName: 'Votre nom', continue: 'Créer et continuer', passwordMismatch: 'Les deux mots de passe ne correspondent pas.' },
    settings: { eyebrow: 'Étape 2 · Configuration', title: 'Une configuration, toute l’équipe.', lead: 'Ces réglages s’appliquent aux annonces de l’entreprise. Les clés secrètes des fournisseurs restent dans la configuration serveur.', company: 'Entreprise et automatisation', demoLocked: 'Aperçu du backoffice : ces réglages sont visibles mais verrouillés dans la démo.', roleLocked: 'Votre rôle permet de consulter ces réglages, pas de les modifier.', sender: 'Nom affiché dans les e-mails', replyTo: 'Adresse de réponse', filterProvider: 'IA de filtrage par défaut', scoreProvider: 'IA d’analyse par défaut', demoMode: 'Mode démo — aucune clé requise', liveMode: 'Mode IA connecté', secretHelp: 'Les clés sont injectées par le développeur dans le serveur. Cette page vérifie leur présence, mais ne reçoit et n’affiche jamais leur valeur.', configured: 'configuré', missing: 'clé manquante', models: 'Choisir précisément les modèles (optionnel)', filterModel: 'Modèle de filtrage', scoreModel: 'Modèle d’analyse', velocity: 'Vélocité de traitement', velocityLead: 'Les workers s’ajustent automatiquement quelques secondes après l’enregistrement.', filterWorkers: 'Filtrages simultanés', scoreWorkers: 'Analyses simultanées', prompts: 'Instructions données aux IA', filterPrompt: 'Prompt de filtrage initial', scorePrompt: 'Prompt de matching et scoring', filterPromptHelp: 'Définit ce qui mérite une analyse approfondie et ce qui est réellement hors périmètre.', scorePromptHelp: 'Définit la méthode de comparaison, de justification et de calcul du score.', retention: 'Conservation et confidentialité', rejectedCvDays: 'Jours de conservation des CV rejetés', selectedCvDays: 'Jours de conservation du CV sélectionné', candidateDataDays: 'Jours avant anonymisation complète', saved: 'Configuration enregistrée.', team: 'Équipe RH', teamLead: 'Tous les membres voient les mêmes annonces et le même suivi.', demoTeamLocked: 'Équipe fictive affichée en lecture seule dans cette sandbox.', add: 'Ajouter', role: 'Rôle', owner: 'Responsable', admin: 'Administrateur', recruiter: 'Recruteur', viewer: 'Lecture seule', sendInvitation: 'Envoyer l’invitation', mfa: 'Double authentification par e-mail', mfaEnabled: 'Activée pour votre compte.', mfaDisabled: 'Désactivée pour votre compte.', enableMfa: 'Activer', disableMfa: 'Désactiver', operations: 'État opérationnel', operationsLead: 'Files et incidents nécessitant une intervention.', queueScreening: 'File filtrage', queueScoring: 'File scoring', queueMail: 'File e-mails', processingFailures: 'Analyses en erreur', mailFailures: 'E-mails à vérifier', failedJobs: 'Jobs échoués', resendInvitation: 'Renvoyer', removeMember: 'Retirer', confirmRemoveMember: 'Retirer définitivement l’accès de {name} ?' },
    dashboard: { title: 'Annonces et suivi', lead: 'Créez une annonce, connectez sa source, puis suivez uniquement ce qui demande votre attention.', welcome: 'Bonjour, {name}', newOffer: 'Créer une annonce', titleField: 'Intitulé du poste', company: 'Entreprise', location: 'Localisation', description: 'Description du poste', criteria: 'Compétences recherchées, séparées par des virgules', criteriaExample: 'Laravel, relation client, anglais…', advanced: 'Messages et IA — réglages avancés', companyDefault: 'Réglage de l’entreprise', rejection: 'Message de rejet hors périmètre', finalRejection: 'Message final aux candidats non retenus', screeningProvider: 'IA de filtrage', scoringProvider: 'IA d’analyse', create: 'Créer l’annonce', applications: '{count} candidatures', empty: 'Aucune annonce pour le moment.', firstOffer: 'Créer la première annonce', integrationCreated: 'Annonce créée · connexion suivante', integrationWarning: 'Copiez cette clé maintenant : elle ne sera plus affichée.', endpoint: 'Point d’entrée API', secret: 'Clé Bearer' },
    campaign: { open: 'Ouvrir les réceptions', close: 'Arrêter les réceptions et préparer le top 10', closingDate: 'Date de clôture', applications: 'Candidatures', empty: 'Aucune candidature reçue.', viewCv: 'Lire le CV', cvDeleted: 'CV purgé', addNote: 'Ajouter une note interne', feedback: 'Message personnalisé dans l’e-mail candidat', saveFeedback: 'Enregistrer le message', feedbackSaved: 'Message ajouté à la réponse candidat.', scopeReason: 'Motif expliqué par l’IA :', select: 'Sélectionner ce candidat', moveUp: 'Monter', moveDown: 'Descendre', confirmSelect: 'Confirmer la sélection finale ? Les autres candidats recevront leur réponse.', confirmReject: 'Confirmer le rejet', continueAnalysis: 'Conserver et scorer', retry: 'Relancer l’analyse', retryMail: 'Relancer l’e-mail', exportData: 'Exporter les données', eraseData: 'Effacer les données personnelles', confirmErase: 'Effacer définitivement les données personnelles de cette candidature ?', score: 'Score', unread: 'Non lu', processing: 'Traitement en cours', integration: 'Connexion ATS / job board', integrationLead: 'Ce point d’entrée privé reçoit les CV PDF depuis LinkedIn, votre ATS ou votre site.', rotateKey: 'Générer une nouvelle clé', rotateWarning: 'La clé précédente sera immédiatement révoquée. Continuer ?', source: 'Source', mail: { pending: 'E-mail en attente', sending: 'Envoi en cours', failed: 'E-mail à vérifier', sent: 'E-mail envoyé', previewed: 'E-mail simulé — aperçu disponible' } },
    tracking: { title: 'Suivre une candidature', lead: 'Utilisez l’identifiant et le jeton privés reçus lors du dépôt.', uuid: 'Identifiant de candidature', token: 'Jeton privé', submit: 'Consulter le statut', score: 'Score final', feedback: 'Retour du recruteur' },
    demo: { banner: 'Sandbox de démonstration', bannerLead: 'Données entièrement fictives · aucun e-mail envoyé · suppression automatique', releaseLead: 'Votre essai est terminé ? Libérez cette place pour le prochain visiteur.', release: 'Se déconnecter et libérer la place', releasing: 'Libération…', releaseConfirm: 'Libérer maintenant cette sandbox ? Toutes ses données fictives seront supprimées et la place redeviendra disponible.', releaseError: 'La sandbox n’a pas pu être libérée. Réessayez dans un instant.', viewSettings: 'Voir la configuration', fictional: '20 candidatures fictives', analysisRunning: 'Les deux files sont en train de travailler.', analysisReady: 'Les analyses sont terminées : produisez maintenant le top 10.', guide: 'Regardez les statuts évoluer, puis clôturez la campagne. Vous pourrez lire, annoter, réordonner, sélectionner un profil et prévisualiser chaque réponse candidat.', processingCount: '{count} analyses restantes', previewMail: 'Voir l’e-mail candidat', mailPreviewLabel: 'Aperçu — aucun envoi', mailPreviewTitle: 'E-mail destiné à {candidate}' },
    status: { draft: 'Brouillon', open: 'Ouverte', closing: 'Clôture en cours', closed: 'Top 10 prêt', selection_made: 'Sélection terminée', received: 'Reçue', screening: 'Filtrage', rejection_proposed: 'Rejet à confirmer', qualified: 'Qualifiée', scoring: 'Analyse fine', scored: 'Scorée', shortlisted: 'Top 10', selected: 'Sélectionnée', rejected_out_of_scope: 'Hors périmètre', rejected_final: 'Non retenue', processing_failed: 'À relancer' },
    common: { loading: 'Chargement…', error: 'Une erreur est survenue.', save: 'Enregistrer', cancel: 'Annuler', close: 'Fermer' },
  },
}

export const i18n = createI18n({
  legacy: false,
  locale: 'fr',
  fallbackLocale: 'fr',
  messages,
  datetimeFormats: { fr: { short: { year: 'numeric', month: 'short', day: 'numeric' } } },
})
